spring:
    application:
        name: summarify
    datasource:
      url: jdbc:postgresql://postgres:5432/summarify
      username: username
      password: password
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate.format_sql: true
